#!/bin/sh
#
# The MIT License (MIT)
#
# Copyright (c) 2018 Olaf Lessenich
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


config="${HOME}/.mbsyncrc"
mail="${HOME}/.mail"

read -p 'Alias (use "-" as directory separator): ' name
read -p 'Server: ' server
read -p 'Username: ' username
read -sp 'Password: ' password

mine="${name}-local"
remote="${name}-remote"
path="${mail}/$(echo ${name} | tr "-" "/")"
inbox="${path}/INBOX"

cat >> $config <<EOF
########################################
# $name
########################################
MaildirStore $mine
Path ${path}/
Inbox $inbox
Flatten .

IMAPStore $remote
Host $server
SSLType STARTTLS
User $username
Pass $password

Channel $name
Master :${remote}:
Slave :${mine}:
Patterns *
Sync All
Create Both
Expunge Both
SyncState *

EOF

if [ ! -d $path ]; then
	mkdir -p $path
fi

chmod 700 $path
chmod 600 $config

sed -i '/^group inboxes.*/d' $config
egrep '^Channel' $config | awk -F' ' '{ print $2":INBOX" }' | xargs echo group inboxes >> $config

echo
