#!/usr/bin/env bash

# usage: $0 dir1 dir2

function usage {
    echo "Usage: $0 [git-diff-options] dir1 dir2"
    exit 1
}

function compare_files {
    echo git diff $diffargs "$1" "$2"
    git diff $diffargs "$1" "$2"
}

diffargs="--no-index"
while [[ "$1" == --* ]]; do
    diffargs="$diffargs $1"
    shift
done

if [ $# -ne 2 ]; then
    usage
fi

diff -rq $1 $2 \
    | awk '/differ$/ {print $2, $4}' \
    | while read file1 file2
do
    echo "Comparing $file1 and $file2"
    compare_files "$file1" "$file2"
done
