#!/bin/sh

set -u
hostname=$(hostname -s)

function setup_panes() {
	session=${1:-}
	shift
	window=${1:-}
	shift
	cmd=${@:-}

	for pane in $(tmux -L console -f ~/.tmux-alternative.conf list-panes -F '#P' -t "${session}:${window}"); do
		tmux -L console -f ~/.tmux-alternative.conf send-keys -t "${session}:${window}.$pane" "${cmd}" C-m
	done
}

function setup_window() {
	session=${1:-}
	window=${2:-}

	if [ "${window}" != "mail" -a "${window}" != "music" -a "${window}" != "top" ]; then
		tmux -L console -f ~/.tmux-alternative.conf split-window -h -t ${session}:${window}.1

		if [ "${window}" == "logs" ]; then
			tmux -L console -f ~/.tmux-alternative.conf split-window -v -t ${session}:${window}.1
			tmux -L console -f ~/.tmux-alternative.conf split-window -v -t ${session}:${window}.3
		else
			tmux -L console -f ~/.tmux-alternative.conf split-window -v -t ${session}:${window}.2
		fi
	fi
}

function setup_session() {
	session=${1:-}
	shift
	tmux -L console -f ~/.tmux-alternative.conf -t ${session} &> /dev/null
	if [ $? != 0 ]
	then
		firstwindow=${1:-}
		shift
		tmux -L console -f ~/.tmux-alternative.conf new-session -s ${session} -n ${firstwindow} -d
		setup_window "${session}" "${firstwindow}"

		windows=${@:-}
		for window in $windows; do
			tmux -L console -f ~/.tmux-alternative.conf new-window -a -n ${window} -t ${session}
			setup_window "${session}" "${window}"
		done
	fi
}

setup_session "console" "mail" "tasks" "logs" "top" "music"
tmux -L console -f ~/.tmux-alternative.conf -t irc &> /dev/null
tmux -L console -f ~/.tmux-alternative.conf -t bash &> /dev/null

tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:tasks.1" "task" C-m

tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:logs.1" "watch-inbox.sh" C-m
tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:logs.2" "synclog" C-m
tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:logs.3" "tail -f ~/.spamlog | cut -d';' --complement -f3" C-m
tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:logs.4" "journalctl -k -f" C-m
tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:top.1" "top" C-m

tmux -L console -f ~/.tmux-alternative.conf send-keys -t "console:mail.1" "mutt" C-m
tmux -L console -f ~/.tmux-alternative.conf select-pane -t "console:mail.1"

tmux -L console -f ~/.tmux-alternative.conf attach -t "console"
