#!/bin/bash

set -eu

infile=$1

while IFS="|" read -r start end project tags description
do
	start="${start/ /T}"
	end="${end/ /T}"
	echo "timew track ${start} - ${end} $project"
	timew track ${start} - ${end} $project
	if [ ! -z "${tags}${description}" ]; then
		annotation="$(echo "${tags} ${description}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
		echo "timew annotate @1 \"${annotation}\""
		timew annotate @1 "${annotation}"
	fi
done < $infile
