#!/bin/bash

set -eu

infile=$1

while IFS="|" read -r start end project tags description
do
	start="${start/ /T}"
	end="${end/ /T}"
	echo "timew track ${start} - ${end} $project"
	timew track ${start} - ${end} $project
	if [ ! -z "$description" ]; then
		echo "timew annotate @1 \"${tags} ${description}\""
		timew annotate @1 "${tags} ${description}"
	fi
done < $infile
